package com.agungsubastian.indosatdigitalcamp;

import java.util.ArrayList;

public class CandiData {
    public static String[][] data = new String[][]{
            {"Borobudur", "Kecamatan Borobudur", "Borobudur adalah sebuah candi Buddha yang terletak di Borobudur, Magelang, Jawa Tengah, Indonesia. Candi ini terletak kurang lebih 100 km di sebelah barat daya Semarang, 86 km di sebelah barat Surakarta, dan 40 km di sebelah barat laut Yogyakarta. Candi berbentuk stupa ini didirikan oleh para penganut agama Buddha Mahayana sekitar tahun 800-an Masehi pada masa pemerintahan wangsa Syailendra. Borobudur adalah candi atau kuil Buddha terbesar di dunia, sekaligus salah satu monumen Buddha terbesar di dunia","https://upload.wikimedia.org/wikipedia/commons/7/77/Stupa_Borobudur.jpg"},
            {"Candi Mendut", "Kecamatan Mungkid", "Candi Mendut adalah sebuah candi bercorak Buddha. Candi yang terletak di Jalan Mayor Kusen Kota Mungkid, Kabupaten Magelang, Jawa Tengah ini, letaknya berada sekitar 3 kilometer dari Candi Borobudur. Candi Mendut didirikan semasa pemerintahan Raja Indra dari dinasti Syailendra. Di dalam prasasti Karangtengah yang bertarikh 824 Masehi, disebutkan bahwa raja Indra telah membangun bangunan suci bernama wenuwana yang artinya adalah hutan bambu. Oleh seorang ahli arkeologi Belanda bernama J.G. de Casparis, kata ini dihubungkan dengan Candi Mendut.","https://upload.wikimedia.org/wikipedia/commons/c/c7/Mendut_Temple_Afternoon.jpg"},
            {"Candi Pawon", "Kecamatan Borobudur", "Nama Candi Pawon tidak dapat diketahui secara pasti asal-usulnya. Ahli epigrafi J.G. de Casparis menafsirkan bahwa Pawon berasal dari bahasa Jawa awu yang berarti 'abu', mendapat awalan pa- dan akhiran -an yang menunjukkan suatu tempat. Dalam bahasa Jawa sehari-hari kata pawon berarti 'dapur', akan tetapi de Casparis mengartikannya sebagai 'perabuan' atau tempat abu. Penduduk setempat juga menyebutkan Candi Pawon dengan nama Bajranalan. Kata ini mungkin berasal dari kata bahasa Sanskerta vajra =yang berarti 'halilintar' dan anala yang berarti 'api'. Candi Pawon dipugar tahun 1903.","https://upload.wikimedia.org/wikipedia/commons/8/8e/Pawon.jpg"},
            {"Candi Ngawen", "Kecamatan Muntilan", "Candi Ngawen adalah candi Buddha yang berada kira-kira 5 km sebelum candi Mendut dari arah Yogyakarta, yaitu di desa Ngawen, kecamatan Muntilan, Kabupaten Magelang. Menurut perkiraan, candi ini dibangun oleh wangsa Sailendra pada abad ke-8 pada zaman Kerajaan Mataram Kuno. Menurut Soekmono keberadaan candi Ngawen ini kemungkinan besar adalah bangunan suci yang tersebut dalam prasasti Karang Tengah pada tahun 824 M, yaitu Venuvana (Sanskerta: 'Hutan Bambu').","https://upload.wikimedia.org/wikipedia/commons/5/56/Ngawen_temple_November_2013.jpg"},
            {"Candi Canggal", "Kecamatan Salam", "Candi ini merupakan candi tertua yang dapat dihubungkan dengan angka tahun. Berdasarkan prasasti Canggal yang ditemukan pada tahun 1879 di reruntuhan, candi ini didirikan pada saat pemerintahan raja Sanjaya dari zaman Kerajaan Mataram Kuno, yaitu pada tahun 732 M (654 tahun Saka). Prasasti ini memiliki banyak informasi berkait dengan Kerajaan Medang atau Mataram Hindu. Berdasarkan prasasti ini, Candi Gunung Wukir mungkin memiliki nama asli Shiwalingga atau Kunjarakunja.","https://upload.wikimedia.org/wikipedia/commons/0/05/Gunung_Wukir_Canggal_Perwara_Temple.jpg"},
            {"Candi Umbul", "Kecamatan Grabag", " ","https://upload.wikimedia.org/wikipedia/commons/4/42/Umbul_Temple%2C_bathing_area%2C_2014-06-20.jpg"},
            {"Candi Bubrah", "Prambanan", "Candi Bubrah adalah salah satu candi Buddha yang berada di dalam kompleks Taman Wisata Candi Prambanan, yaitu di antara Percandian Rara Jonggrang dan Candi Sewu. Secara administratif, candi ini terletak di Dukuh Bener, Desa Bugisan, Kecamatan Prambanan, Kabupaten Klaten, Provinsi Jawa Tengah. Dinamakan 'Bubrah' karena keadaan candi ini rusak (bubrah dalam bahasa Jawa) sejak ditemukan. Menurut perkiraan, candi ini dibangun pada abad ke-9 pada zaman Kerajaan Mataram Kuno, satu periode dengan Candi Sewu. Candi ini mempunyai ukuran 12 m x 12 m terbuat dari jenis batu andesit, dengan sisa reruntuhan setinggi 2 meter saja. Saat ditemukan masih terdapat beberapa arca Buddha, walaupun tidak utuh lagi. Sekarang, kegiatan pemugaran sedang dilaksanakan untuk merekonstruksi bangunan candi ini. Kegiatan pemugaran dimulai pada tahun 2016 dan diperkirakan selesai pada tahun 2017.","https://upload.wikimedia.org/wikipedia/commons/3/3b/Bubrah09_4.jpg"},
            {"Candi Prambanan", "Prambanan", "Candi Prambanan atau Candi Roro Jonggrang adalah kompleks candi Hindu terbesar di Indonesia yang dibangun pada abad ke-9 masehi. Candi ini dipersembahkan untuk Trimurti, tiga dewa utama Hindu yaitu Brahma sebagai dewa pencipta, Wishnu sebagai dewa pemelihara, dan Siwa sebagai dewa pemusnah. Berdasarkan prasasti Siwagrha nama asli kompleks candi ini adalah Siwagrha (bahasa Sanskerta yang bermakna 'Rumah Siwa'), dan memang di garbagriha (ruang utama) candi ini bersemayam arca Siwa Mahadewa setinggi tiga meter yang menujukkan bahwa di candi ini dewa Siwa lebih diutamakan.","https://upload.wikimedia.org/wikipedia/commons/6/66/Yogyakarta_Indonesia_Prambanan-temple-complex-02.jpg"},
            {"Candi Plaosan", "Prambanan", "Candi Plaosan adalah sebutan untuk kompleks percandian yang terletak di Dukuh Plaosan, Desa Bugisan, Kecamatan Prambanan, Kabupaten Klaten, Provinsi Jawa Tengah, Indonesia. Candi ini terletak kira-kira satu kilometer ke arah timur-laut dari Candi Sewu atau Candi Prambanan. Adanya kemuncak stupa, arca Buddha, serta candi-candi perwara (pendamping/kecil) yang berbentuk stupa menandakan bahwa candi-candi tersebut adalah candi Buddha. Kompleks ini dibangun pada abad ke-9 oleh Raja Rakai Pikatan dan Sri Kahulunan pada zaman Kerajaan Medang, atau juga dikenal dengan nama Kerajaan Mataram Kuno.","https://upload.wikimedia.org/wikipedia/commons/d/d6/Plaosan_Temple.jpg"},
            {"Candi Sewu", "Prambanan", "Candi Sewu atau Manjusrighra adalah candi Buddha yang dibangun pada abad ke-8 Masehi yang berjarak hanya delapan ratus meter di sebelah utara Candi Prambanan. Candi Sewu merupakan kompleks candi Buddha terbesar kedua setelah Candi Borobudur di Jawa Tengah. Candi Sewu berusia lebih tua daripada Candi Borobudur dan Prambanan. Meskipun aslinya memiliki 249 candi, oleh masyarakat setempat candi ini dinamakan \"Sewu\" yang berarti seribu dalam bahasa Jawa. Penamaan ini berdasarkan kisah legenda Loro Jonggrang.","https://upload.wikimedia.org/wikipedia/commons/2/26/Candi_Sewu_viewed_from_the_south%2C_23_November_2013.jpg"},
            {"Candi Lumbung", "Prambanan", "Candi Lumbung adalah salah satu kompleks percandian Buddha yang berada di dalam kompleks Taman Wisata Candi Prambanan, yaitu di sebelah candi Bubrah. Meskipun demikian, Candi ini telah masuk ke wilayah Jawa Tengah, yaitu di Kabupaten Klaten.","https://upload.wikimedia.org/wikipedia/commons/1/1e/Candi_Lumbung.JPG"},
            {"Candi Sojiwan", "Prambanan", "Candi Sojiwan atau Candi Sajiwan adalah sebuah candi Buddhis yang terletak di desa Kebon Dalem Kidul, kecamatan Prambanan, kabupaten Klaten, Jawa Tengah. Sebuah ciri khas candi ini ialah adanya sekitar 20 relief di kaki candi yang berhubungan dengan cerita-cerita Pancatantra atau Jataka dari India. Dari 20 relief ini, tinggal 19 relief yang sekarang masih ada. Candi ini terletak kurang lebih dua kilometer ke arah selatan dari Candi Prambanan, dari gerbang Taman Wisata Candi Prambanan meyeberang jalan raya Solo-Yogyakarta masuk ke jalan kecil menuju ke arah selatan, menyeberang rel kereta api, lalu pada perempatan pertama berbelok ke kiri (timur) sejauh beberapa ratus meter hingga candi terlihat di sisi selatan. Candi ini telah rampung dipugar pada tahun 2011.","https://upload.wikimedia.org/wikipedia/commons/8/89/Sajiwan_main.JPG"},
            {"Candi Merak", "Karangnongko", "Candi Merak adalah peninggalan purbakala berupa kompleks percandian di Dukuh Candi, Desa Karangnongko, Kecamatan Karangnongko, Kabupaten Klaten, Jawa Tengah. Lokasi ini berada di sebelah barat laut dari wilayah Klaten, berbatasan dengan Kabupaten Boyolali dan Kabupaten Sleman. Candi Merak berdiri di atas lahan seluas 1.480 meter persegi. Kompleks candi terdiri atas satu bangunan induk dan tiga candi perwara. Candi ini didirikan sekitar abad ke-9-10, yaitu pada zaman Kerajaan Mataram Kuno. Penelitian atas Candi Merak dilakukan sejak tahun 1925/1926 oleh Dinas Purbakala. Sementara itu, pemugaran Candi Merak dilakukan secara bertahap dan pada tahun 2011 telah selesai dengan pemasangan batu sungkup atap meskipun bagian kemuncak belum ditemukan. Di sekitar Candi Merak terdapat berbagai peninggalan purbakala lain seperti Candi Karangnongko, Candi Kriyan, dan Candi Bekelan.","https://upload.wikimedia.org/wikipedia/commons/0/02/COLLECTIE_TROPENMUSEUM_Indo-Javaanse_tempel_bij_Karangnongko_tijdens_of_na_de_opgraving_TMnr_60044019.jpg"},
//            {"", "", "",""},
//            {"", "", "",""},
//            {"", "", "",""},
//            {"", "", "",""},
//            {"", "", "",""},
    };
    public static ArrayList<Candi> getListData(){
        ArrayList<Candi> list = new ArrayList<>();
        for (String[] aData : data) {
            Candi candi = new Candi();
            candi.setNama(aData[0]);
            candi.setAsal(aData[1]);
            candi.setDeskripsi(aData[2]);
            candi.setPhoto(aData[3]);
            list.add(candi);
        }
        return list;
    }
}
